modLoader="javafml"
loaderVersion="[43,)"
license="MIT"

[[mods]]
modId="qlogin"
version="${version}"
displayName="QLogin"
logoFile="assets/qlogin/icon.png"
credits="aqing"
authors="aqing"
description="""
§bQLogin 玩家登录认证系统§r - 支持注册、登录、密码管理、IP封禁
适配 Minecraft 1.19.2 (Forge)
"""

[[dependencies.qlogin]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="SERVER"

[[dependencies.qlogin]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="SERVER"
