modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="qlogin"
version="${version}"
displayName="QLogin"
logoFile="assets/qlogin/icon.png"
credits="aqing"
authors="aqing"
description="""
§bQLogin 玩家登录认证系统§r - 支持注册、登录、密码管理、IP封禁
适配 Minecraft 1.20.1 (NeoForge)
"""

[[dependencies.qlogin]]
    modId="neoforge"
    mandatory=true
    versionRange="[20,)"
    ordering="NONE"
    side="SERVER"

[[dependencies.qlogin]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="SERVER"
