name: ${project.name}
version: ${project.version}
main: top.chenray.qlogin.paper.QLoginPaper
api-version: 1.12
description: ${project.description}
author: aqing
database: false

commands:
  login:
    description: 登录到服务器
    usage: /<command> <密码>
    aliases: [l]
  register:
    description: 注册账号
    usage: /<command> <密码> <确认密码>
    aliases: [reg]
  logout:
    description: 退出登录
    usage: /<command>
  changepassword:
    description: 修改密码
    usage: /<command> <旧密码> <新密码>
    aliases: [changepw, cpw]

permissions:
  qlogin.admin:
    description: 管理员权限
    default: op
